USE [master]
GO

/****** Object:  Database [Commands]    Script Date: 3/04/2020 6:59:30 PM ******/
CREATE DATABASE [Commands]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Commands', FILENAME = N'd:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Commands.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Commands_log', FILENAME = N'd:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Commands_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Commands].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Commands] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Commands] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Commands] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Commands] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Commands] SET ARITHABORT OFF 
GO

ALTER DATABASE [Commands] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Commands] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Commands] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Commands] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Commands] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Commands] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Commands] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Commands] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Commands] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Commands] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Commands] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Commands] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Commands] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Commands] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Commands] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Commands] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Commands] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Commands] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Commands] SET  MULTI_USER 
GO

ALTER DATABASE [Commands] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Commands] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Commands] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Commands] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Commands] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Commands] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Commands] SET  READ_WRITE 
GO


